# Generated by Django 5.2.4 on 2025-07-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
