# Generated by Django 5.2.4 on 2025-07-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='detail',
        ),
        migrations.AddField(
            model_name='task',
            name='body',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
